
name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate the Snake Contribution Graph (Dark Mode)
      uses: Platane/snk/svg-only@v2
      with:
        github_user_name: Kingpin98k
        out_file: dist/github-snake-dark.svg
        prefers_dark_mode: true

    - name: Check Repository Status
      run: git status

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add dist/github-snake-dark.svg
        git commit -m "Update snake contribution graph [skip ci]"
        git push origin main
